# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mess_Manager.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(545, 454)
        self.stackedWidget = QtGui.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(-1, -1, 541, 451))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.pushButton = QtGui.QPushButton(self.page)
        self.pushButton.setGeometry(QtCore.QRect(340, 350, 171, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.groupBox = QtGui.QGroupBox(self.page)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 281, 131))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet(_fromUtf8("color :rgb(255, 255, 255)"))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 46, 13))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 46, 13))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 90, 46, 13))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(60, 30, 181, 20))
        self.lineEdit.setStyleSheet(_fromUtf8("color : rgb(0, 0, 0)"))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 60, 181, 20))
        self.lineEdit_2.setStyleSheet(_fromUtf8("color : rgb(0, 0, 0)"))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(60, 90, 181, 20))
        self.lineEdit_3.setStyleSheet(_fromUtf8("color : rgb(0, 0, 0)"))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.label_6 = QtGui.QLabel(self.page)
        self.label_6.setGeometry(QtCore.QRect(10, 220, 161, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(_fromUtf8("color :rgb(255, 255, 255)"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.tableWidget = QtGui.QTableWidget(self.page)
        self.tableWidget.setGeometry(QtCore.QRect(10, 260, 301, 151))
        self.tableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(140)
        self.line = QtGui.QFrame(self.page)
        self.line.setGeometry(QtCore.QRect(-10, 190, 551, 21))
        self.line.setMidLineWidth(4)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label = QtGui.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(340, 300, 61, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("color :rgb(255, 255, 255)"))
        self.label.setObjectName(_fromUtf8("label"))
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.page)
        self.doubleSpinBox.setGeometry(QtCore.QRect(410, 300, 121, 22))
        self.doubleSpinBox.setMaximum(49999.99)
        self.doubleSpinBox.setSingleStep(500.0)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.label_2 = QtGui.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 161, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(_fromUtf8("color :rgb(255, 255, 255)"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_7 = QtGui.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(5, 2, 541, 451))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_13 = QtGui.QLabel(self.page)
        self.label_13.setGeometry(QtCore.QRect(330, 390, 201, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet(_fromUtf8("color :rgb(255, 255, 255)"))
        self.label_13.setText(_fromUtf8(""))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_7.raise_()
        self.pushButton.raise_()
        self.groupBox.raise_()
        self.label_6.raise_()
        self.tableWidget.raise_()
        self.line.raise_()
        self.label.raise_()
        self.doubleSpinBox.raise_()
        self.label_2.raise_()
        self.label_13.raise_()
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.label_8 = QtGui.QLabel(self.page_2)
        self.label_8.setGeometry(QtCore.QRect(20, 20, 271, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet(_fromUtf8("color :rgb(255, 255, 255)"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.page_2)
        self.label_9.setGeometry(QtCore.QRect(20, 70, 141, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet(_fromUtf8("color :rgb(255, 255, 255)"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.page_2)
        self.label_10.setGeometry(QtCore.QRect(20, 110, 141, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet(_fromUtf8("color :rgb(255, 255, 255)"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lineEdit_4 = QtGui.QLineEdit(self.page_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(180, 70, 231, 20))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.lineEdit_5 = QtGui.QLineEdit(self.page_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(180, 110, 231, 20))
        self.lineEdit_5.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.pushButton_2 = QtGui.QPushButton(self.page_2)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 180, 191, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.label_11 = QtGui.QLabel(self.page_2)
        self.label_11.setGeometry(QtCore.QRect(20, 150, 441, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet(_fromUtf8("color :rgb(255, 255, 255)"))
        self.label_11.setText(_fromUtf8(""))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.page_2)
        self.label_12.setGeometry(QtCore.QRect(0, 0, 551, 451))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_12.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.lineEdit_4.raise_()
        self.lineEdit_5.raise_()
        self.pushButton_2.raise_()
        self.label_11.raise_()
        self.stackedWidget.addWidget(self.page_2)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.pushButton.setText(_translate("Form", "Enter Mess Charge", None))
        self.groupBox.setTitle(_translate("Form", "Your Information", None))
        self.label_3.setText(_translate("Form", "Name", None))
        self.label_4.setText(_translate("Form", "ID", None))
        self.label_5.setText(_translate("Form", "Hall", None))
        self.label_6.setText(_translate("Form", "Mess Charges", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Student ID", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Student Name", None))
        self.label.setText(_translate("Form", "Amount", None))
        self.label_2.setText(_translate("Form", "Welcome Torvaltz", None))
        self.label_7.setText(_translate("Form", "TextLabel", None))
        self.label_8.setText(_translate("Form", "Mess Manager Login", None))
        self.label_9.setText(_translate("Form", "Mess Manager ID", None))
        self.label_10.setText(_translate("Form", "Password", None))
        self.pushButton_2.setText(_translate("Form", "Login", None))
        self.label_12.setText(_translate("Form", "TextLabel", None))

